Repository international-labour-organization/designsystem, pull requests merged in 2023-11, with the labels that each got.

#621 Fix/Fonts: Overpass missing glyphs in Vietnamese.
  .changeset/large-planes-bake.md
  packages/fonts/assets/Overpass-Black.ttf
  packages/fonts/assets/Overpass-BlackItalic.ttf
  packages/fonts/assets/Overpass-Bold.eot
  packages/fonts/assets/Overpass-Bold.ttf
  packages/fonts/assets/Overpass-Bold.woff
  packages/fonts/assets/Overpass-Bold.woff2
  packages/fonts/assets/Overpass-BoldItalic.eot
  packages/fonts/assets/Overpass-BoldItalic.ttf
  packages/fonts/assets/Overpass-BoldItalic.woff
  packages/fonts/assets/Overpass-BoldItalic.woff2
  packages/fonts/assets/Overpass-ExtraBold.ttf
  packages/fonts/assets/Overpass-ExtraBoldItalic.ttf
  packages/fonts/assets/Overpass-ExtraLight.ttf
  packages/fonts/assets/Overpass-ExtraLightItalic.ttf
  packages/fonts/assets/Overpass-Italic.eot
  packages/fonts/assets/Overpass-Italic.ttf
  packages/fonts/assets/Overpass-Italic.woff
  packages/fonts/assets/Overpass-Italic.woff2
  packages/fonts/assets/Overpass-Light.eot
  packages/fonts/assets/Overpass-Light.ttf
  packages/fonts/assets/Overpass-Light.woff
  packages/fonts/assets/Overpass-Light.woff2
  packages/fonts/assets/Overpass-LightItalic.ttf
  packages/fonts/assets/Overpass-Medium.ttf
  packages/fonts/assets/Overpass-MediumItalic.ttf
  packages/fonts/assets/Overpass-Regular.eot
  packages/fonts/assets/Overpass-Regular.ttf
  packages/fonts/assets/Overpass-Regular.woff
  packages/fonts/assets/Overpass-Regular.woff2
  packages/fonts/assets/Overpass-SemiBold.eot
  packages/fonts/assets/Overpass-SemiBold.ttf
  packages/fonts/assets/Overpass-SemiBold.woff
  packages/fonts/assets/Overpass-SemiBold.woff2
  packages/fonts/assets/Overpass-SemiBoldItalic.eot
  packages/fonts/assets/Overpass-SemiBoldItalic.ttf
  packages/fonts/assets/Overpass-SemiBoldItalic.woff
  packages/fonts/assets/Overpass-SemiBoldItalic.woff2
  packages/fonts/assets/Overpass-Thin.ttf
  packages/fonts/assets/Overpass-ThinItalic.ttf
  packages/fonts/assets/overpass-v13-cyrillic-ext_latin-ext_vietnamese-300.woff2
  packages/fonts/assets/overpass-v13-cyrillic-ext_latin-ext_vietnamese-500.woff2
  packages/fonts/assets/overpass-v13-cyrillic-ext_latin-ext_vietnamese-500italic.woff2
  packages/fonts/assets/overpass-v13-cyrillic-ext_latin-ext_vietnamese-700.woff2
  packages/fonts/assets/overpass-v13-cyrillic-ext_latin-ext_vietnamese-700italic.woff2
  packages/fonts/font-css/fonts.css
  packages/fonts/index.scss
Labels: Release 1 Nov 2023

#622 Fix(twig/styles): make accordion work properly in modal
  .changeset/shy-sheep-hammer.md
  packages/styles/scss/components/_accordion.scss
  packages/twig/src/patterns/components/accordion/accordion-item.twig
  packages/twig/src/patterns/components/accordion/accordion.js
  packages/twig/src/patterns/components/accordion/accordion.twig
  packages/twig/src/patterns/components/modal/modal.twig
Labels: Release 1 Nov 2023

#616 Fix(styles): Callout
  .changeset/quiet-horses-agree.md
  packages/styles/scss/components/_callout.scss
  packages/twig/src/patterns/components/callout/callout.twig
  packages/twig/src/patterns/components/callout/callout.wingsuit.yml
Labels: Release 1 Nov 2023

#614 Fix(styles/twig): profile component
  .changeset/cuddly-carrots-care.md
  packages/styles/scss/components/_profile.scss
  packages/twig/src/patterns/components/profile/profile.twig
  packages/twig/src/patterns/components/profile/profile.wingsuit.yml
Labels: Release 1 Nov 2023

#612 Fix(styles): scrollbar appearing in tab content
  .changeset/mighty-garlics-shake.md
  packages/styles/scss/components/_tabs.scss
Labels: Release 1 Nov 2023

#611 Fix(twig/styles): align source to bottom of stat card
  .changeset/wicked-paws-protect.md
  packages/styles/scss/components/_card.scss
  packages/styles/scss/components/_statcard.scss
  packages/twig/src/patterns/components/card_stat/card_stat.twig
Labels: Release 1 Nov 2023

#608 fix(styles): make logo appear in nav in Firefox
  .changeset/proud-gorillas-confess.md
  packages/styles/scss/components/_navigation.scss
Labels: Release 1 Nov 2023

#623 Fix/Twig: Clicking on Search header causes dropdown to close
  .changeset/strong-hats-decide.md
  packages/twig/src/patterns/components/navigation/navigation.js
Labels: Release 6 Nov 2023

#667 Fix(Style): Refactor and fix RTL style in linklist
  .changeset/dull-boxes-collect.md
  packages/styles/scss/components/_footer.scss
  packages/styles/scss/components/_linklist.scss
Labels: rtl

#668 Refactor RTL style using dir in searchfield
  .changeset/silly-taxis-travel.md
  packages/styles/scss/components/_searchfield.scss
Labels: rtl

#672 Refactor RTL style using dir in text area
  .changeset/gold-turkeys-change.md
  packages/styles/scss/components/_formcontrol.scss
  packages/styles/scss/components/_textarea.scss
Labels: rtl

#673 Refactor RTL style using dir in cards
  .changeset/flat-ghosts-invent.md
  packages/styles/scss/components/_card.scss
  packages/styles/scss/components/_cardgroup.scss
  packages/styles/scss/components/_detailcard.scss
  packages/styles/scss/components/_featurecard.scss
  packages/styles/scss/components/_multilinkcard.scss
  packages/styles/scss/components/_promocard.scss
  packages/styles/scss/components/_textcard.scss
Labels: rtl

#680 Fix(Style): Support rtl in dropdown
  .changeset/happy-cheetahs-marry.md
  packages/styles/scss/components/_dropdown.scss
Labels: rtl

#681 Fix(Style): Support rtl in navigation
  .changeset/gold-cows-grab.md
  packages/styles/scss/components/_navigation.scss
Labels: rtl

#682 Fix(Style): Clean up unwanted RTL style in tag
  .changeset/popular-carpets-protect.md
  packages/styles/scss/components/_tag.scss
Labels: rtl

#683 Fix(Style): Refactor rtl to use dir in richtext
  .changeset/nine-kangaroos-matter.md
  packages/styles/scss/components/_richtext.scss
Labels: rtl

#684 Refactor rtl to use dir in social media
  .changeset/slimy-seas-drive.md
  packages/styles/scss/components/_socialmedia.scss
Labels: rtl

#685 Fix(Style): Refactor rtl to use dir in video
  .changeset/smart-flies-thank.md
  packages/styles/scss/components/_video.scss
Labels: rtl
